version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - chmod +x gradlew
  build:
    commands:
      - ./gradlew clean build
artifacts:
  files:
    - build/libs/oboss-demoapp-backend-0.0.1-SNAPSHOT.war
    - appspec.yml
    - scripts/**
